### ISSUE TITLE
Template updates are not propagated to existing jobs.

### ISSUE THREAD

**Issue by jamestalmage** [entagen/jenkins-build-per-branch#48]
This can be accomplished by deleting feature-branch jobs and letting them get recreated from the new template, but you lose your build history.

**Comment by jamesdh** [comment]
This is actually intended. Even though master may evolve over time, a given branch may *require* that its job configs be consistent with when the branch was initially created and not update to latest master. 

In addition, this would imply on some setups that hundreds or even thousands of jobs get deleted and then recreated every time a change is made to the master job, which in turn would cause a flood of jobs being executed. We've been down this road, and it's no fun.

Instead, what we did locally was setup a parameterized job that takes a regex for determining what jobs to delete, and then kicks off jenkins-build-per-branch to recreate them. This allows us to be much more selective.

Closing since we don't consider this a bug.
